# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/references.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_references(object):
    def setupUi(self, references):
        references.setObjectName("references")
        references.resize(800, 600)
        self.gridLayout_2 = QtWidgets.QGridLayout(references)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox = QtWidgets.QGroupBox(references)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 450))
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.fname = QtWidgets.QLineEdit(self.groupBox)
        self.fname.setObjectName("fname")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fname)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.mname = QtWidgets.QLineEdit(self.groupBox)
        self.mname.setObjectName("mname")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.mname)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lname = QtWidgets.QLineEdit(self.groupBox)
        self.lname.setObjectName("lname")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.lname)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.phone = QtWidgets.QLineEdit(self.groupBox)
        self.phone.setObjectName("phone")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.phone)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.email = QtWidgets.QLineEdit(self.groupBox)
        self.email.setObjectName("email")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.email)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.street = QtWidgets.QLineEdit(self.groupBox)
        self.street.setObjectName("street")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.street)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.city = QtWidgets.QLineEdit(self.groupBox)
        self.city.setObjectName("city")
        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.FieldRole, self.city)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.state = QtWidgets.QComboBox(self.groupBox)
        self.state.setObjectName("state")
        self.formLayout_2.setWidget(12, QtWidgets.QFormLayout.FieldRole, self.state)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.LabelRole, self.label_9)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.formLayout_2.setLayout(14, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.zip = QtWidgets.QLineEdit(self.groupBox)
        self.zip.setObjectName("zip")
        self.formLayout_2.setWidget(13, QtWidgets.QFormLayout.FieldRole, self.zip)
        self.title = QtWidgets.QLineEdit(self.groupBox)
        self.title.setObjectName("title")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.title)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_10)
        self.employer = QtWidgets.QLineEdit(self.groupBox)
        self.employer.setObjectName("employer")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.employer)
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        self.label_11.setObjectName("label_11")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.phoneType = QtWidgets.QComboBox(self.groupBox)
        self.phoneType.setObjectName("phoneType")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.phoneType)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(references)
        QtCore.QMetaObject.connectSlotsByName(references)

    def retranslateUi(self, references):
        _translate = QtCore.QCoreApplication.translate
        references.setWindowTitle(_translate("references", "ResumeBuilder"))
        self.groupBox.setTitle(_translate("references", "Reference"))
        self.label.setText(_translate("references", "First Name"))
        self.label_2.setText(_translate("references", "Middle Name"))
        self.label_3.setText(_translate("references", "Last Name"))
        self.label_4.setText(_translate("references", "Phone Number"))
        self.label_5.setText(_translate("references", "Email"))
        self.label_6.setText(_translate("references", "Street"))
        self.label_7.setText(_translate("references", "City"))
        self.label_8.setText(_translate("references", "State"))
        self.label_9.setText(_translate("references", "Zip"))
        self.label_10.setText(_translate("references", "Title"))
        self.label_11.setText(_translate("references", "Employer"))
        self.pushButton.setText(_translate("references", "Remove"))
        self.pushButton_2.setText(_translate("references", "Clear"))

