# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/school.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_school(object):
    def setupUi(self, school):
        school.setObjectName("school")
        school.resize(800, 600)
        self.gridLayout_2 = QtWidgets.QGridLayout(school)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(school)
        self.groupBox.setMinimumSize(QtCore.QSize(400, 400))
        self.groupBox.setObjectName("groupBox")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout_2.setObjectName("formLayout_2")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.formLayout_2.setLayout(10, QtWidgets.QFormLayout.LabelRole, self.formLayout)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.name = QtWidgets.QLineEdit(self.groupBox)
        self.name.setMaximumSize(QtCore.QSize(300, 16777215))
        self.name.setObjectName("name")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.startDate = QtWidgets.QDateEdit(self.groupBox)
        self.startDate.setMaximumSize(QtCore.QSize(300, 16777215))
        self.startDate.setCalendarPopup(True)
        self.startDate.setObjectName("startDate")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.startDate)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setObjectName("checkBox")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.checkBox)
        self.dateString = QtWidgets.QLineEdit(self.groupBox)
        self.dateString.setMaximumSize(QtCore.QSize(300, 16777215))
        self.dateString.setObjectName("dateString")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dateString)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.endDate = QtWidgets.QDateEdit(self.groupBox)
        self.endDate.setMaximumSize(QtCore.QSize(300, 16777215))
        self.endDate.setCalendarPopup(True)
        self.endDate.setObjectName("endDate")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.endDate)
        self.degree = QtWidgets.QLineEdit(self.groupBox)
        self.degree.setMaximumSize(QtCore.QSize(300, 16777215))
        self.degree.setObjectName("degree")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.degree)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.pushButton_2)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.state = QtWidgets.QComboBox(self.groupBox)
        self.state.setMaximumSize(QtCore.QSize(200, 16777215))
        self.state.setObjectName("state")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.state)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.school_type_edit = QtWidgets.QLineEdit(self.groupBox)
        self.school_type_edit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.school_type_edit.setObjectName("school_type_edit")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.school_type_edit)
        self.school_type = QtWidgets.QComboBox(self.groupBox)
        self.school_type.setMaximumSize(QtCore.QSize(200, 16777215))
        self.school_type.setObjectName("school_type")
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.school_type)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.city = QtWidgets.QLineEdit(self.groupBox)
        self.city.setMaximumSize(QtCore.QSize(300, 16777215))
        self.city.setObjectName("city")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.city)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.zip = QtWidgets.QLineEdit(self.groupBox)
        self.zip.setMaximumSize(QtCore.QSize(300, 16777215))
        self.zip.setObjectName("zip")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.zip)
        self.gridLayout.addWidget(self.groupBox, 0, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(school)
        QtCore.QMetaObject.connectSlotsByName(school)

    def retranslateUi(self, school):
        _translate = QtCore.QCoreApplication.translate
        school.setWindowTitle(_translate("school", "ResumeBuilder"))
        self.groupBox.setTitle(_translate("school", "Education"))
        self.label_2.setText(_translate("school", "School"))
        self.label.setText(_translate("school", "Start Date"))
        self.startDate.setDisplayFormat(_translate("school", "M/d/yyyy"))
        self.checkBox.setText(_translate("school", "Present"))
        self.label_3.setText(_translate("school", "End Date"))
        self.endDate.setDisplayFormat(_translate("school", "M/d/yyyy"))
        self.label_4.setText(_translate("school", "Degree"))
        self.pushButton.setText(_translate("school", "Remove"))
        self.pushButton_2.setText(_translate("school", "Clear"))
        self.label_5.setText(_translate("school", "State"))
        self.label_6.setText(_translate("school", "School Type"))
        self.label_7.setText(_translate("school", "City"))
        self.label_8.setText(_translate("school", "ZIP Code"))

